version: '3.2'

services: 
<<<<<<< HEAD
  # mongodb:
  #   image: 
  sample-rest-mongo:
=======
  springboot-rest-mongo:
>>>>>>> 92a22a594c8cf23abc7f3539b6d352ebf0d2b4b4
    image: ashif14/sample-rest-mongo
    container_name: springboot-rest-mongo
    # environment: 
      # - MONGO_HOST=mongodb-master
      # - MONGO_PORT=27017
      # - MONGO_DB=ecommerce
      # - APP_PORT=8089
    ports: 
      - 8080
    volumes:
      - type: volume
        source: logs
        target: /logs
    networks: 
      - mongodb_mongo_net
      - replicaset_mongo_net
volumes:
  logs:
networks: 
  mongodb_mongo_net:
    external: true
  replicaset_mongo_net:
    external: true
